USE ocrgw;

-- 임의의 이미지 키 더미 데이터 삽입
INSERT INTO OCR_BATCH_TRGT_IMAG (OCR_WORK_TRGT_IMAG_ID, SYS_DT, STATUS) VALUES ('IMG_20260601_0001', NOW(), 'COMPLETED');
INSERT INTO OCR_BATCH_TRGT_IMAG (OCR_WORK_TRGT_IMAG_ID, SYS_DT, STATUS) VALUES ('IMG_20260601_0002', NOW(), 'COMPLETED');
INSERT INTO OCR_BATCH_TRGT_IMAG (OCR_WORK_TRGT_IMAG_ID, SYS_DT, STATUS) VALUES ('IMG_20260601_0003', NOW(), 'PROCESSING');
INSERT INTO OCR_BATCH_TRGT_IMAG (OCR_WORK_TRGT_IMAG_ID, SYS_DT, STATUS) VALUES ('IMG_20260601_0004', DATE_SUB(NOW(), INTERVAL 1 HOUR), 'PENDING');
INSERT INTO OCR_BATCH_TRGT_IMAG (OCR_WORK_TRGT_IMAG_ID, SYS_DT, STATUS) VALUES ('IMG_20260601_0005', DATE_SUB(NOW(), INTERVAL 2 HOUR), 'ERROR');
