-- 데이터베이스(스키마) 생성
CREATE DATABASE IF NOT EXISTS ocrgw DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE ocrgw;

-- 이미지키 처리 내역 테이블 생성
CREATE TABLE IF NOT EXISTS OCR_BATCH_TRGT_IMAG (
    OCR_WORK_TRGT_IMAG_ID VARCHAR(255) NOT NULL COMMENT '추출된 이미지 키 (기본키)',
    SYS_DT DATETIME NOT NULL COMMENT '처리 일시',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '작업 상태 (PENDING, PROCESSING, COMPLETED, ERROR)',
    PRIMARY KEY (OCR_WORK_TRGT_IMAG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='배치 처리용 이미지 키 저장 테이블';
