# Application DB - MariaDB
spring.datasource.base.app.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.base.app.url=jdbc:mariadb://127.0.0.1:3306/ocr?useSSL=false&characterEncoding=UTF-8
spring.datasource.base.app.username=root
spring.datasource.base.app.password=1234
spring.datasource.base.app.encryption=false

# Spring Data JPA Auto-configuration
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/ocr?useSSL=false&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
