### 파일 업로드시 ###
file.storage.location=d:\\test\\image\\

### 리브레오피스 ###
office.home=/

### 애비워드 ###
abiword.home=/

### imagemagic ###
magick.path=/
magick.command.density=150

### 고스트스트립트경로 ###
ghostscript.path=/
