### 파일 업로드시 ###
file.storage.location=/home/cjh/backend

### imagemagic ###
magick.path=/home/ocrgw/imagemagick/bin/magick
magick.command.density=150

### ghostscript ###
ghostscript.path=/home/ocrgw/ghostscript/ghostscript-10.06.0/bin/gs