# 기본패스워드
authorize.user.password.default-password=qhdkscjfwj1!

# 비밀번호 룰
authorize.user.password.length=8
authorize.user.password.has-symbol=false
authorize.user.password.duplicate-with-id=false

# 반복규칙 - 0: 적용안함
authorize.user.password.max-continuous-length=2 

# 비밀번호 변경 주기
authorize.user.password.change-days=90
authorize.user.password.reuse-check=true
authorize.user.password.error-max-count=10