# inzisoft 이미지 암복호화 솔루션 key 경로
inzisoft.image.encryption.key.path=/home/ocrgw/inzisoft/sSecu/key/inzi_enc_nhlife_image.dat

# inzisoft 이미지 암복호화 솔루션 license 경로
inzisoft.image.encryption.license.path=/home/ocrgw/inzisoft/sSecu/license/inzisoft.crypt.LDIGTC02.20260225_OP.csl

# inzisoft 이미지 압축해제 솔루션 license 경로
inzisoft.image.convert.license.path=/home/ocrgw/inzisoft/sConverter/license/inzi.license.nhlife.LDIGTC02.20260226_OP.xml



# 암복호화 파일 저장 경로
image.settings.encFilePath=d:\\test\\image\\enc\\

# image download path
image.settings.downloadPath=d:\\test\\image\\

# 서버 아이피
image.settings.ecm.serverIp=localhost

# 서버 포트
image.settings.ecm.serverPort=9088

# ecm 로그인 아이디
image.settings.ecm.userId=admin

# ecm 로그인 패스워드
image.settings.ecm.userPw=12345qwert