# 기본적인 환경 설정파일 정보
server.servlet.session.timeout=600
server.servlet.encoding.force-response=true
server.port=9081

spring.profiles.active=dev

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.codec.max-in-memory-size=10MB

spring.jackson.default-property-inclusion=NON_NULL
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.chain.strategy.content.enabled=true
spring.web.resources.chain.strategy.content.paths=/**
spring.sql.init.encoding=utf-8

spring.aop.proxy-target-class=false
spring.cache.type=simple