### 파일 업로드시 ###
file.storage.location=/home/cjh/backend

### 리브레오피스 ###
office.home=/

### 애비워드 ###
abiword.home=/

### imagemagic ###
magick.path=/home/ocrgw/imagemagick/bin/magick
magick.command.density=150

### ghostscript ###
ghostscript.path=/home/ocrgw/ghostscript/ghostscript-10.06.0/bin/gs