# Application DB - MariaDB
spring.datasource.base.app.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.base.app.url=jdbc:mariadb://127.0.0.1:3306/ocrgw?useSSL=false&characterEncoding=UTF-8
spring.datasource.base.app.username=root
spring.datasource.base.app.password=root
spring.datasource.base.app.encryption=false

# Spring Data JPA Auto-configuration
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/ocrgw?useSSL=false&characterEncoding=UTF-8
# spring.datasource.username=root
# spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect


# # Application DB - 커넥션 풀 설정
spring.datasource.base.app.hikari.connection-timeout=30000
spring.datasource.base.app.hikari.maximum-pool-size=30
spring.datasource.base.app.hikari.minimum-idle=10
spring.datasource.base.app.hikari.idle-timeout=600000
spring.datasource.base.app.hikari.max-lifetime=1800000
spring.datasource.base.app.hikari.pool-name=collection-pool