# upstage api 관련 설정
api.settings.ocr.upstage.name=api-ocr-local
api.settings.ocr.upstage.url=http://localhost:8080
api.settings.ocr.upstage.timeout=60000
api.settings.ocr.upstage.retry=3
api.settings.ocr.upstage.maxConnections=50
api.settings.ocr.upstage.pendingAcquireTimeout=3
api.settings.ocr.upstage.authentication.name=ocrgateway-api
api.settings.ocr.upstage.authentication.value=
api.settings.ocr.upstage.authentication.bearer=up_ab8VCiAPyAkqsO1lQ0SGTjvNaADC3
api.settings.ocr.upstage.authentication.mapping=
api.settings.ocr.upstage.resources.ocr.uri=/inference
api.settings.ocr.upstage.resources.ocr.use=true
api.settings.ocr.upstage.resources.healthcheck.uri=/health
api.settings.ocr.upstage.resources.healthcheck.use=true

# EAI api 관련 설정
api.settings.eai.name=api-eai-local
api.settings.eai.url=http://localhost:8082
api.settings.eai.timeout=60000
api.settings.eai.retry=3
api.settings.eai.maxConnections=50
api.settings.eai.pendingAcquireTimeout=3
api.settings.eai.authentication.name=ocrgateway-api
api.settings.eai.authentication.value=
api.settings.eai.authentication.bearer=eai_ab8VCiAPyAkqsO1lQ0SGTjvNaADC3
api.settings.eai.authentication.mapping=
api.settings.eai.resources.ocr.uri=/inference
api.settings.eai.resources.ocr.use=true
api.settings.eai.resources.healthcheck.uri=/health
api.settings.eai.resources.healthcheck.use=true