# Application DB -  MySQL
spring.datasource.base.app.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.base.app.url=jdbc:mysql://10.176.32.202:13636/ocr?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
spring.datasource.base.app.username=ocr
spring.datasource.base.app.password=qhdkscjfwj1!
spring.datasource.base.app.encryption=false